### ISSUE TITLE
Can we use to detect eye contact in adults (20 - 30years) too?

### ISSUE THREAD

**Issue by amit-syadav** [ejcgt/eye-contact-cnn#1]

**Comment by ejcgt** [comment]
Hello,

Thank you for the question and sorry about my late response.

We haven't quantitatively evaluated the model on adult subjects, but from my experience it would still work reasonably well. If you have a target dataset for a specific use case, I would recommend trying out the model as is, and if then you observe a domain gap issue try fine-tuning it further based on it. Please feel free to email me if you want to discuss it more.
